/// This file is generated from generate.py.
/// Re-generate it if you upgrade to a new version of RocksDB.

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum DBStatisticsTickerType {
    BlockCacheMiss = 0,
    BlockCacheHit = 1,
    BlockCacheAdd = 2,
    BlockCacheAddFailures = 3,
    BlockCacheIndexMiss = 4,
    BlockCacheIndexHit = 5,
    BlockCacheIndexAdd = 6,
    BlockCacheIndexBytesInsert = 7,
    BlockCacheIndexBytesEvict = 8,
    BlockCacheFilterMiss = 9,
    BlockCacheFilterHit = 10,
    BlockCacheFilterAdd = 11,
    BlockCacheFilterBytesInsert = 12,
    BlockCacheFilterBytesEvict = 13,
    BlockCacheDataMiss = 14,
    BlockCacheDataHit = 15,
    BlockCacheDataAdd = 16,
    BlockCacheDataBytesInsert = 17,
    BlockCacheBytesRead = 18,
    BlockCacheBytesWrite = 19,
    BloomFilterUseful = 20,
    BloomFilterFullPositive = 21,
    BloomFilterFullTruePositive = 22,
    BloomFilterMicros = 23,
    PersistentCacheHit = 24,
    PersistentCacheMiss = 25,
    SimBlockCacheHit = 26,
    SimBlockCacheMiss = 27,
    MemtableHit = 28,
    MemtableMiss = 29,
    GetHitL0 = 30,
    GetHitL1 = 31,
    GetHitL2AndUp = 32,
    CompactionKeyDropNewerEntry = 33,
    CompactionKeyDropObsolete = 34,
    CompactionKeyDropRangeDel = 35,
    CompactionKeyDropUser = 36,
    CompactionRangeDelDropObsolete = 37,
    CompactionOptimizedDelDropObsolete = 38,
    CompactionCancelled = 39,
    NumberKeysWritten = 40,
    NumberKeysRead = 41,
    NumberKeysUpdated = 42,
    BytesWritten = 43,
    BytesRead = 44,
    NumberDbSeek = 45,
    NumberDbNext = 46,
    NumberDbPrev = 47,
    NumberDbSeekFound = 48,
    NumberDbNextFound = 49,
    NumberDbPrevFound = 50,
    IterBytesRead = 51,
    NoFileCloses = 52,
    NoFileOpens = 53,
    NoFileErrors = 54,
    StallL0SlowdownMicros = 55,
    StallMemtableCompactionMicros = 56,
    StallL0NumFilesMicros = 57,
    StallMicros = 58,
    DbMutexWaitMicros = 59,
    RateLimitDelayMillis = 60,
    NoIterators = 61,
    NumberMultigetCalls = 62,
    NumberMultigetKeysRead = 63,
    NumberMultigetBytesRead = 64,
    NumberFilteredDeletes = 65,
    NumberMergeFailures = 66,
    BloomFilterPrefixChecked = 67,
    BloomFilterPrefixUseful = 68,
    NumberOfReseeksInIteration = 69,
    GetUpdatesSinceCalls = 70,
    BlockCacheCompressedMiss = 71,
    BlockCacheCompressedHit = 72,
    BlockCacheCompressedAdd = 73,
    BlockCacheCompressedAddFailures = 74,
    WalFileSynced = 75,
    WalFileBytes = 76,
    WotrFileSynced = 77,
    WotrFileBytes = 78,
    WriteDoneBySelf = 79,
    WriteDoneByOther = 80,
    WriteTimedout = 81,
    WriteWithWal = 82,
    CompactReadBytes = 83,
    CompactWriteBytes = 84,
    FlushWriteBytes = 85,
    WriteWithWotr = 86,
    NumberDirectLoadTableProperties = 87,
    NumberSuperversionAcquires = 88,
    NumberSuperversionReleases = 89,
    NumberSuperversionCleanups = 90,
    NumberBlockCompressed = 91,
    NumberBlockDecompressed = 92,
    NumberBlockNotCompressed = 93,
    MergeOperationTotalTime = 94,
    FilterOperationTotalTime = 95,
    RowCacheHit = 96,
    RowCacheMiss = 97,
    ReadAmpEstimateUsefulBytes = 98,
    ReadAmpTotalReadBytes = 99,
    NumberRateLimiterDrains = 100,
    NumberIterSkip = 101,
    BlobDbNumPut = 102,
    BlobDbNumWrite = 103,
    BlobDbNumGet = 104,
    BlobDbNumMultiget = 105,
    BlobDbNumSeek = 106,
    BlobDbNumNext = 107,
    BlobDbNumPrev = 108,
    BlobDbNumKeysWritten = 109,
    BlobDbNumKeysRead = 110,
    BlobDbBytesWritten = 111,
    BlobDbBytesRead = 112,
    BlobDbWriteInlined = 113,
    BlobDbWriteInlinedTtl = 114,
    BlobDbWriteBlob = 115,
    BlobDbWriteBlobTtl = 116,
    BlobDbBlobFileBytesWritten = 117,
    BlobDbBlobFileBytesRead = 118,
    BlobDbBlobFileSynced = 119,
    BlobDbBlobIndexExpiredCount = 120,
    BlobDbBlobIndexExpiredSize = 121,
    BlobDbBlobIndexEvictedCount = 122,
    BlobDbBlobIndexEvictedSize = 123,
    BlobDbGcNumFiles = 124,
    BlobDbGcNumNewFiles = 125,
    BlobDbGcFailures = 126,
    BlobDbGcNumKeysOverwritten = 127,
    BlobDbGcNumKeysExpired = 128,
    BlobDbGcNumKeysRelocated = 129,
    BlobDbGcBytesOverwritten = 130,
    BlobDbGcBytesExpired = 131,
    BlobDbGcBytesRelocated = 132,
    BlobDbFifoNumFilesEvicted = 133,
    BlobDbFifoNumKeysEvicted = 134,
    BlobDbFifoBytesEvicted = 135,
    TxnPrepareMutexOverhead = 136,
    TxnOldCommitMapMutexOverhead = 137,
    TxnDuplicateKeyOverhead = 138,
    TxnSnapshotMutexOverhead = 139,
    NumberMultigetKeysFound = 140,
    NoIteratorCreated = 141,
    NoIteratorDeleted = 142,
    BlockCacheCompressionDictMiss = 143,
    BlockCacheCompressionDictHit = 144,
    BlockCacheCompressionDictAdd = 145,
    BlockCacheCompressionDictBytesInsert = 146,
    BlockCacheCompressionDictBytesEvict = 147,
    TitanNumGet,
    TitanNumSeek,
    TitanNumNext,
    TitanNumPrev,
    TitanBlobFileNumKeysWritten,
    TitanBlobFileNumKeysRead,
    TitanBlobFileBytesWritten,
    TitanBlobFileBytesRead,
    TitanBlobFileSynced,
    TitanGcNumFiles,
    TitanGcNumNewFiles,
    TitanGcNumKeysOverwritten,
    TitanGcNumKeysRelocated,
    TitanGcBytesOverwritten,
    TitanGcBytesRelocated,
    TitanGcBytesWritten,
    TitanGcBytesRead,
    TitanBlobCacheHit,
    TitanBlobCacheMiss,
    TitanGcNoNeed,
    TitanGcRemain,
    TitanGcDiscardable,
    TitanGcSample,
    TitanGcSmallFile,
    TitanGcFailure,
    TitanGcSuccess,
    TitanGcTriggerNext,
}
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(C)]
pub enum DBStatisticsHistogramType {
    DbGet = 0,
    DbWrite = 1,
    CompactionTime = 2,
    CompactionCpuTime = 3,
    SubcompactionSetupTime = 4,
    TableSyncMicros = 5,
    CompactionOutfileSyncMicros = 6,
    WalFileSyncMicros = 7,
    ManifestFileSyncMicros = 8,
    TableOpenIoMicros = 9,
    DbMultiget = 10,
    ReadBlockCompactionMicros = 11,
    ReadBlockGetMicros = 12,
    WriteRawBlockMicros = 13,
    StallL0SlowdownCount = 14,
    StallMemtableCompactionCount = 15,
    StallL0NumFilesCount = 16,
    HardRateLimitDelayCount = 17,
    SoftRateLimitDelayCount = 18,
    NumFilesInSingleCompaction = 19,
    DbSeek = 20,
    WriteStall = 21,
    SstReadMicros = 22,
    NumSubcompactionsScheduled = 23,
    BytesPerRead = 24,
    BytesPerWrite = 25,
    BytesPerMultiget = 26,
    BytesCompressed = 27,
    BytesDecompressed = 28,
    CompressionTimesNanos = 29,
    DecompressionTimesNanos = 30,
    ReadNumMergeOperands = 31,
    BlobDbKeySize = 32,
    BlobDbValueSize = 33,
    BlobDbWriteMicros = 34,
    BlobDbGetMicros = 35,
    BlobDbMultigetMicros = 36,
    BlobDbSeekMicros = 37,
    BlobDbNextMicros = 38,
    BlobDbPrevMicros = 39,
    BlobDbBlobFileWriteMicros = 40,
    BlobDbBlobFileReadMicros = 41,
    BlobDbBlobFileSyncMicros = 42,
    BlobDbGcMicros = 43,
    BlobDbCompressionMicros = 44,
    BlobDbDecompressionMicros = 45,
    FlushTime = 46,
    SstBatchSize = 47,
    DbWriteWalTime = 48,
    DbWriteWotrTime = 49,
    HistogramEnumMax = 50,
    TitanKeySize,
    TitanValueSize,
    TitanGetMicros,
    TitanSeekMicros,
    TitanNextMicros,
    TitanPrevMicros,
    TitanBlobFileWriteMicros,
    TitanBlobFileReadMicros,
    TitanBlobFileSyncMicros,
    TitanManifestFileSyncMicros,
    TitanGcMicros,
    TitanGcInputFileSize,
    TitanGcOutputFileSize,
    TitanIterTouchBlobFileCount,
}
